name: evimero
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.3+1
  url_launcher: ^6.1.12
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.5
  wave: ^0.2.2

dev_dependencies:

  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons: 
  android: true 
  ios: true 
  image_path: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/backgrounds/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont.ttf
